server.port=${PORT:8080}

# 🚫 DISABLE DATABASE (IMPORTANT)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Mail
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

spring.main.lazy-initialization=true

app.mail.from-name=My Mail App

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://email-generation-system-c6ly.vercel.app